apiVersion: v1
kind: ResourceQuota
metadata:
  name: pods-high
#  namespace: namespace
spec:
  hard:
    pods: "10"
    cpu: "1000"
    memory: 200Gi
    requests.cpu: "4"
    limits.cpu: "10"
    requests.memory: 5Gi
    limits.memory: 10Gi
  scopeSelector:
    matchExpressions:
      - operator: In
        scopeName: PriorityClass
        values: ["high"]
